### PR TITLE
chore(tfhe): fix typos

### PR DESCRIPTION
**Pull request by miles-six**
chore(tfhe): fix typos @IceTDrinker 
I re-pull request #980  and want to add workflow for codespell check to eliminate typos in the future.

I have added a relatively simple filtering file to exclude certain words. 

If you find it meaningful, you can modify the filtering conditions according to your needs.

### Check-list:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by miles-six** [comment]
If you dont need this workflow you can just delete the file about codespell

**Comment by IceTDrinker** [comment]
hey @miles-six we will likely use the typos crate from rust in a workflow, so for now I think there is no need to add the workflow and the other files to your PR :) 

You can amend your commit and force push here 👍

**Comment by IceTDrinker** [comment]
@miles-six we'll take the typos correction with pleasure, we'll manage the CI ourselves !

**Comment by miles-six** [comment]
> @miles-six we'll take the typos correction with pleasure, we'll manage the CI ourselves !

I'm sorry, sir. It's just that I'm not very familiar with Git commands, so I've been repeatedly deleting my forked repository to make submissions.

**Pull request closed without merging**
