### PR TITLE
chore(tfhe): fix typos

### PR DESCRIPTION
**Pull request by miles-six**
chore(tfhe):fix typos 
@IceTDrinker   sorry sir, now it should right?

### Check-list:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
yes thank you @miles-six I just want to say you can force push instead of re-opening PRs :) thanks for your contribution !

**Comment by miles-six** [comment]
> yes thank you @miles-six I just want to say you can force push instead of re-opening PRs :) thanks for your contribution !

yes,thank you. Waiting for be merged!

**Review by IceTDrinker — APPROVED** [review]
Thanks !

Some workflows will likely fail, we have a known issue for external contributors, the linters should work fine

**Comment by IceTDrinker** [comment]
FYI for github contribution I think this gist is helpful https://gist.github.com/MarcDiethelm/7303312

**Comment by IceTDrinker** [comment]
@miles-six can you give me the rights to edit your PR ? the commit format is missing a space after the `:` I can do the fix so you don't have to fork again (see the gist above to have easier workflows :) )

see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by miles-six** [comment]
> @miles-six can you give me the rights to edit your PR ? the commit format is missing a space after the `:` I can do the fix so you don't have to fork again (see the gist above to have easier workflows :) )
> 
> see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

of course you can do, so how can i give you right?

**Comment by IceTDrinker** [comment]
> > @miles-six can you give me the rights to edit your PR ? the commit format is missing a space after the `:` I can do the fix so you don't have to fork again (see the gist above to have easier workflows :) )
> > see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> of course you can do, so how can i give you right?

there must be a check box on the right and if you scroll down, look at the documentation they show how it looks like

**Comment by miles-six** [comment]
image
yes

**Comment by IceTDrinker** [comment]
ah ok thanks ! I'll see to update it then

**Comment by miles-six** [comment]
> ah ok thanks ! I'll see to update it then

Thank you for your patience！

**Comment by IceTDrinker** [comment]
looks like I cannot update the commit myself so what you should do is to go on your commit, ammend to add a white space after the `:` and then force push, it will update your branch and the PR

**Comment by miles-six** [comment]
@IceTDrinker  You are the most patient person I have ever encountered, and I truly appreciate your patience and guidance

**Comment by IceTDrinker** [comment]
> @IceTDrinker You are the most patient person I have ever encountered, and I truly appreciate your patience and guidance

Thank you for the kind words, I think it should be good, now I'll check and let the workflows run !

**Pull request merged**
