### PR TITLE
refactor(shortint): refactor the shortint keyswitching code

### PR DESCRIPTION
**Pull request by IceTDrinker**
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/670

### PR content/description

- this manages better all the cases we encouter, we force a refresh PBS in all cases for now which is less optimal in certain cases but allows to be safe in cases where keyswitches might be chained

cc @titouantanguy to check the cases which were failing previously

### CODE REVIEW

**Comment by IceTDrinker** [comment]
I'll push a second commit tomorrow that will have an edge case test which this code fixes

**Comment by titouantanguy** [comment]
Seems to be working now! (based on 1 test). Running a more extensive test suit but it'll take some time.

**Comment by IceTDrinker** [comment]
> Seems to be working now! (based on 1 test). Running a more extensive test suit but it'll take some time.

Added a test with something more similar to what you do, test passes, so should be fine hoepfully

**Review by tmontaigu — APPROVED** [review]

**Comment by IceTDrinker** [comment]
I'll let you guys merge this, I'll likely be off before I can, please include it in the alpha.2 of monday @nsarlin-zama

**Pull request merged**
