### PR TITLE
chore(ci): select benches to run

### PR DESCRIPTION
**Pull request by IceTDrinker**

### CODE REVIEW

**Comment by IceTDrinker** [comment]
not sure if this works on push, wdyt @soonum ?

I needed something similar to this to run only select benchmarks for multi bit, thought I might as well try to open a PR

**Comment by IceTDrinker** [comment]
example run with this approach https://github.com/zama-ai/tfhe-rs/actions/runs/5485024318/jobs/9993301864

**Comment by IceTDrinker** [comment]
alright looks like input is not given to the push event

**Comment by soonum** [comment]
> alright looks like input is not given to the push event

Yes it makes sense, since `push` event and `workflow_dispatch` are two different beasts.
Maybe add another step that does the original call to Slab (i.e using the matrix build). This step would be run only if the event is `push`. Conversely the one you've modified would only be run in case of `workflow_dispatch`.

**Comment by IceTDrinker** [comment]
test run : https://github.com/zama-ai/tfhe-rs/actions/runs/5486276852/jobs/9996168151 with only boolean

**Review by tmontaigu — APPROVED** [review]

**Pull request merged**
