### PR TITLE
chore(ci): test examples and apps in the ci

### PR DESCRIPTION
**Pull request by soonum**
This workflow would run once a Pull Request is approved by a reviewer.

### CODE REVIEW

**Comment by soonum** [comment]
@slab-ci examples_apps_test

**Comment by IceTDrinker** [comment]
didn't we say we wanted to launch them in the AWS CPU tests ?

**Comment by tmontaigu** [comment]
> didn't we say we wanted to launch them in the AWS CPU tests ?

Yes

**Comment by soonum** [comment]
Oh I misunderstood !

**Comment by soonum** [comment]
Simple diff then :smiley:

**Review by IceTDrinker — APPROVED** [review]
So we were already running the tests for examples except dark market ?

**Pull request merged**
