### PR TITLE
chore(ci): add workflow to trigger all benchmarks automatically

### PR DESCRIPTION
**Pull request by soonum**
This workflow enables benchmarks automation. It will be called on each push in `main`, and with a workflow-dispatch capability if one wants to run all benchmarks in one go outside a PR.

### CODE REVIEW

**Comment by soonum** [comment]
Just testing benchmark commands by the way :wink: 

@slab-ci boolean_bench
@slab-ci shortint_bench

**Review by IceTDrinker — APPROVED** [review]
Looks good thanks !

**Review by IceTDrinker — APPROVED** [review]

**Comment by soonum** [comment]
@slab-ci boolean_bench

**Review by IceTDrinker — APPROVED** [review]

**Comment by soonum** [comment]
@slab-ci boolean_bench

**Comment by soonum** [comment]
@slab-ci boolean_bench

**Comment by soonum** [comment]
@slab-ci shortint_bench

**Pull request merged**
