### PR TITLE
fix(shortint): use correct value to shift msg in bivariate bps

### PR DESCRIPTION
**Pull request by tmontaigu**
fixes zama-ai/tfhe-rs-internal#32

### CODE REVIEW

**Comment by IceTDrinker** [comment]
should we go ahead with this review ?

**Comment by tmontaigu** [comment]
Hm, I would rather propose as a PR the smaller change, and later do a refactor of the function_bivariate functions

**Comment by IceTDrinker** [comment]
ok !

**Comment by tmontaigu** [comment]
closed as #141 is a better fix

**Pull request closed without merging**
