### PR TITLE
update estimator script

### PR DESCRIPTION
**Pull request by bencrts**
WIP: will request a review when ready

Updating the parameter scripts in the CI

### CODE REVIEW

**Comment by IceTDrinker** [comment]
@bencrts we have a PR coming with updated parameters https://github.com/zama-ai/tfhe-rs/pull/1233 for the boolean failure

**Comment by bencrts** [comment]
thanks, no worries, I'm just going to point the estimator back to main and then we can merge this whenever you're ready!

**Comment by IceTDrinker** [comment]
PR has been merged, don't hesitate to ping @soonum when you need to get ready to merge !

**Comment by IceTDrinker** [comment]
@soonum this can be closed given the PR you merged right ?

**Pull request closed without merging**
