### PR TITLE
docs(tfhe): updated user documentation and API documentation

### PR DESCRIPTION
**Pull request by IceTDrinker**

### CODE REVIEW

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
@slab_ci cpu_test

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
failed test on M1 is a flaky one, re ran the test when I was at the office, let me know if it's good to merge @jborfila

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Review by jborfila — APPROVED** [review]

**Pull request merged**
