### PR TITLE
fix(integer): StaticSignedBigInt right shift

### PR DESCRIPTION
**Pull request by tmontaigu**
### Check-list:

* [x] Tests for the changes have been added (for bug fixes / features)

### CODE REVIEW

**Review by IceTDrinker — APPROVED** [review]
Can you quickly indicate what wrong value we were getting before ?

**Comment by tmontaigu** [comment]
For -1 >> 1 we were getting [0, 0, 0, u64::MAX], so 64 `1` in the MSB then zeros
when we expect 2 `1` in MSB and the rest to be zero

**Comment by IceTDrinker** [comment]
ok arithmetic shift

**Comment by tmontaigu** [comment]
Yes but we were putting the value of the sign bit all over the most significant block and not only in places where sign bits would actually need to be used as padding

**Pull request merged**
