### PR TITLE
feat(gpu): add signed addition

### PR DESCRIPTION
**Pull request by agnesLeroy**
closes: _please link all relevant issues_

### Check-list:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by agnesLeroy** [comment]
@tmontaigu here's a first idea to implement signed operations. I haven't seen a difference in the comparison implementations on CPU between signed and unsigned, and for now there are no overflowing ops on GPU, so I'm really not sure this would be a good way to do it.

**Comment by tmontaigu** [comment]
> tmontaigu here's a first idea to implement signed operations. I haven't seen a difference in the comparison implementations on CPU between signed and unsigned, and for now there are no overflowing ops on GPU, so I'm really not sure this would be a good way to do it. I could try to implement the signed casts to see how it looks maybe.

There are differences in comparisons https://github.com/zama-ai/tfhe-rs/blob/f0b4749aca33c38baabc0424a01e275c33fc315a/tfhe/src/integer/server_key/comparator.rs#L422

Also to match the CPU api, we need a different type for signed ciphertexts, also we want tests for every signed operation, no matter if they are the same as unsigned

**Comment by tmontaigu** [comment]
Ok I Saw the CudaSignedRadixCiphertext which is good, but I would still be better to do a few opetations per PR and and the corresponding tests

**Comment by agnesLeroy** [comment]
Thank you very much, I'll do that :slightly_smiling_face:

**Comment by tmontaigu** [comment]
@agnesLeroy this can be closed right ?

**Pull request closed without merging**
