### PR TITLE
fix(ci): fix secret on CI checkout

### PR DESCRIPTION
**Pull request by mayeul-zama**

### CODE REVIEW

**Review by IceTDrinker — COMMENTED** [review]
check the least access rule here when possible

**Comment by soonum** [comment]
> check the least access rule here when possible

I have an idea regarding that.
1. replacing all usage of `FHE_ACTIONS_TOKEN` for downloading Slab repo to `SLAB_ACTIONS_TOKEN`
2. reducing permissions to read-only whenever possible for `FHE_ACTIONS_TOKEN`
3. creating a new token for the releases since it needs a write permission in the repo

The second step will need careful analysis to avoid side-effect that could pop-up later.

**Comment by IceTDrinker** [comment]
Ok, should this be merged and then what you propose done later ?

**Comment by IceTDrinker** [comment]
Ok, should this be merged and then what you propose done later ?

**Review by soonum — APPROVED** [review]

**Pull request merged**
