### PR TITLE
chore(tfhe): fix typos

### PR DESCRIPTION
**Pull request by miles-six**
chore(tfhe): fix typos:

### PR content/description

I discovered 91 typos in a total of 38 files. Then I merged them together.

The code quality is exceptionally high, so sincerely hope my PR can help make this repository more standardized.

### Check-list:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
hello @miles-six the commit format is not compliant

the format here should be :

chore(tfhe): fix typos

Thanks for the patch, please update the commit text and we'll launch the CI to merge

**Review by IceTDrinker — CHANGES_REQUESTED** [review]
need proper commit format, requesting changes for now

**Comment by IceTDrinker** [comment]
hey @miles-six you updated the name of the PR, but the commit message has not changed see here: https://github.com/zama-ai/tfhe-rs/pull/980/commits

**Comment by IceTDrinker** [comment]
@miles-six hey, we do not accept merge commits, could you please rebase on top of main instead ? thank you

**Comment by IceTDrinker** [comment]
@miles-six please just force push on that branch

**Comment by miles-six** [comment]
I will re-pull-request it and add workflow to check all the typos

**Pull request closed without merging**
