### PR TITLE
refactor(core): use avx512 intrinsics when available for data conversions

### PR DESCRIPTION
**Pull request by IceTDrinker**

### CODE REVIEW

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test
@slab-ci cpu_integer_test
@slab-ci cpu_multi_bit_test
@slab-ci cpu_wasm_test
@slab-ci csprng_randomness_testing

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test
@slab-ci cpu_integer_test
@slab-ci cpu_multi_bit_test

**Comment by IceTDrinker** [comment]
actually there appears to be no rounding, but it should be fine in our case for the native case as we rescale things to [-2^63, 2^63[ which is a 2^64 wide interval, we end up with only proper integer values in the floating point domain, the 2^63 edge case seems to be handled well

**Comment by sarah-ek** [comment]
what we need is VCVTTPD2QQ instead of VCVTPD2QQ, since i think we want rounding with truncation

**Comment by IceTDrinker** [comment]
indeed to match the existing behavior

**Comment by IceTDrinker** [comment]
with 0.4.0 released and the AVX512 enabled integer test + updated conversion tests I feel confident moving ahead with this @sarah-ek :)

**Review by sarah-ek — APPROVED** [review]

**Pull request merged**
