### PR TITLE
refactor(all): derive serde::{Serialize, Deserialize}

### PR DESCRIPTION
**Pull request by tmontaigu**
This replaces our manual implementations of serde's Serialize and Deserialize trait with 'derives'.

The manual implementetions were needed when using concrete-core but as tfhe-rs does not use concrete-core's engines we can simply derive the implementations.

Closes zama-ai/tfhe-rs-internal#16

### CODE REVIEW

**Comment by IceTDrinker** [comment]
perhaps this https://github.com/marketplace/actions/s3-cache-for-github-actions ?

**Comment by IceTDrinker** [comment]
could you add a "closes: #link_to_issue_number" in the description of your PR so that it gets closed automatically ?

We may be missing a PR template at the moment for this

**Comment by IceTDrinker** [comment]
maybe there is a way to make bincode optional and only enable it for internal-keycache, c-api and wasm-api

**Comment by tmontaigu** [comment]
> maybe there is a way to make bincode optional and only enable it for internal-keycache, c-api and wasm-api

Adding bincode as an optional dep and making the relevant c-api / wasm-ap feature enable bincode should work

**Comment by IceTDrinker** [comment]
for C and wasm we have the __c_api and __wasm_api features

**Comment by IceTDrinker** [comment]
we'll probably encounter the keycache issue again, I'll purge the cache on the S3 bucket and let this PR rebuild it

**Review by IceTDrinker — APPROVED** [review]
Thanks a lot ! This helps declutter our code a bit, though the discussion about magic numbers to avoid issues during deserialization may force us to re-write/prepare a macro to manage that

**Pull request merged**
