### PR TITLE
chore(zk): update arkworks to 0.5.0

### PR DESCRIPTION
**Pull request by nsarlin-zama**
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/573 https://github.com/zama-ai/tfhe-rs-internal/issues/813

### PR content/description
Update arkworks to 0.5.0

### CODE REVIEW

**Review by IceTDrinker — APPROVED** [review]
Can you launch both ZK bench on this branch ?

Pending no performance regression this is good to go !

**Comment by nsarlin-zama** [comment]
> Can you launch both ZK bench on this branch ?
> 
> Pending no performance regression this is good to go !

I ran `make bench_integer_zk` and `make bench_web_js_api_parallel_chrome` and have noticed no regression

**Comment by IceTDrinker** [comment]
> > Can you launch both ZK bench on this branch ?
> > Pending no performance regression this is good to go !
> 
> I ran `make bench_integer_zk` and `make bench_web_js_api_parallel_chrome` and have noticed no regression

using the actions workflows ?

**Comment by nsarlin-zama** [comment]
> > > Can you launch both ZK bench on this branch ?
> > > Pending no performance regression this is good to go !
> > 
> > 
> > I ran `make bench_integer_zk` and `make bench_web_js_api_parallel_chrome` and have noticed no regression
> 
> using the actions workflows ?

oh no I did it manually on an aws instance, I will re-run using the workflow

**Pull request merged**
