### PR TITLE
feat(wasm): add missing push_u{512,1024,2048}

### PR DESCRIPTION
**Pull request by tmontaigu**
This adds the missing push functions for some big
uint type that the fhEVM needs

### Check-list:

* [x] Tests for the changes have been added (for bug fixes / features)

### CODE REVIEW

**Review by IceTDrinker — COMMENTED** [review]
Thanks can you first push the version bump to be able to prepare alpha 3 ?

**Comment by tmontaigu** [comment]
In the same PR or another ?

**Comment by IceTDrinker** [comment]
this one I think in an additional commit as discussed on Slack

**Review by IceTDrinker — APPROVED** [review]
Thanks !

**Pull request merged**
