### PR TITLE
chore(ci): use large ubuntu runner to get more disk space

### PR DESCRIPTION
**Pull request by soonum**

### CODE REVIEW

**Review by IceTDrinker — APPROVED** [review]
Thanks !

**Comment by IceTDrinker** [comment]
@soonum lint and check not happy with custom runner name

**Comment by soonum** [comment]
> Will need to update the branch requirements, otherwise looks good

Yes once the PR is merged

**Comment by IceTDrinker** [comment]
you will need to update to merge the PR to remove the old ubuntu cehck

**Pull request merged**
