### PR TITLE
Docs fix spelling issues

### PR DESCRIPTION
**Pull request by nnsW3**
Hello
I fixed several minor spelling issues.

### CODE REVIEW

**Comment by IceTDrinker** [comment]
Hello @nnsW3 

thanks for the contribution, as you can see we need you to sign a CLA before we can move ahead with your PR 🙂

**Comment by nnsW3** [comment]
> Hello @nnsW3
> 
> thanks for the contribution, as you can see we need you to sign a CLA before we can move ahead with your PR 🙂

done

**Comment by aquint-zama** [comment]
@cla-bot check

**Comment by IceTDrinker** [comment]
Hello @nnsW3 could you please create a single commit and respect our commit format please ?

check our main branch for examples of format, this would be a chore commit.

the regex for the first line is `pattern: '^((feat|fix|chore|refactor|style|test|docs|doc)(\([\w\-_]+\))?\!?\:) .+$'`

**Comment by IceTDrinker** [comment]
@nnsW3 open https://github.com/zama-ai/tfhe-rs/pull/1703 instead with you as co-author in the commit cheers

**Pull request closed without merging**
