### PR TITLE
fix(gpu): fix a bug that allow pbs_buffer to be initialized with a different max_shared_memory than the one provided by the user

### PR DESCRIPTION
**Pull request by pdroalves**
closes: _please link all relevant issues_

### Check-list:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Review by agnesLeroy — COMMENTED** [review]
Hey @pdroalves! Sorry I don't get how this fixes a bug :sweat_smile: cuda get max shared memory shoud always return  the same value on a given device no?

**Comment by agnesLeroy** [comment]
Hmm, actually I think what we really want is query the device every time we need to know the max shared memory amount: we shouldn't give the possibility to overwrite that value.

**Comment by pdroalves** [comment]
Yes, that would be better. We have an opened issued for some time to remove that parameter from all entry points. Should we do that instead?

**Comment by agnesLeroy** [comment]
Yeah that would be great I think :slightly_smiling_face:

**Pull request closed without merging**
