### PR TITLE
chore(gpu): update gpu parameters

### PR DESCRIPTION
**Pull request by guillermo-oyarzun**
closes: _please link all relevant issues_

### Check-list:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Review by agnesLeroy — COMMENTED** [review]
Looks good to me! @IceTDrinker is it ok if we add only one set of params in the 2-64 file? Do we need the GPU to use 2-64 parameters for the next release?

**Comment by IceTDrinker** [comment]
2^-40 parameters will be removed only 2^-64 will remain

are you sure about the pfail of those parameters btw ?

**Comment by guillermo-oyarzun** [comment]
@IceTDrinker, those parameters were generated with the optimizer without using the bind_crypto method, so the pfail constraint should've been imposed correctly. Do we have another way to validate the pfail?

**Comment by IceTDrinker** [comment]
> @IceTDrinker, those parameters were generated with the optimizer without using the bind_crypto method, so the pfail constraint should've been imposed correctly. Do we have another way to validate the pfail?

there is a branch from Sam here: https://github.com/zama-ai/concrete-spec/tree/tfhers

there is a multi bit experiment that can likely be updated with your cost model

**Comment by IceTDrinker** [comment]
I'm guessing those are the updated GPU params using the branch we discussed ?

**Comment by guillermo-oyarzun** [comment]
> I'm guessing those are the updated GPU params using the branch we discussed ?

Yup, we managed to generate them with the help of Sam. We also ran the pfail -40 just for comparison purposes.

**Comment by IceTDrinker** [comment]
> > I'm guessing those are the updated GPU params using the branch we discussed ?
> 
> Yup, we managed to generate them with the help of Sam. We also ran the pfail -40 just for comparison purposes.

all right, let me check something on my end

**Comment by agnesLeroy** [comment]
@IceTDrinker we're good to merge that PR I think, do you confirm?

**Comment by IceTDrinker** [comment]
> @IceTDrinker we're good to merge that PR I think, do you confirm?

Let me run some last checks as discussed :) but likely it will be good yes !

**Pull request merged**
