### PR TITLE
chore(tfhe): rename integer ilog2 operations

### PR DESCRIPTION
**Pull request by soonum**

### CODE REVIEW

**Review by IceTDrinker — APPROVED** [review]
Thanks !

**Comment by IceTDrinker** [comment]
looks like some methods have an issue with signed types

**Review by IceTDrinker — APPROVED** [review]

**Comment by IceTDrinker** [comment]
you are getting a thing in gpu clippy, wut

**Comment by agnesLeroy** [comment]
@soonum I pushed a small commit to the branch to fix GPU clippy, for some reason it complained on smthg it hadn't caught before.

**Pull request merged**
