### PR TITLE
chore(ci): use aws ami with the latest updates

### PR DESCRIPTION
**Pull request by soonum**

### CODE REVIEW

**Review by IceTDrinker — CHANGES_REQUESTED** [review]
looks to be failing, in any case we won't merge this until the start of next quarter (too risky for the CI)

No need to focus on this right away and thank you !

**Comment by soonum** [comment]
It was failing because the AMI wasn't ready I think. I relaunch now.
@slab-ci cpu_fast_test

**Review by IceTDrinker — APPROVED** [review]

**Review by IceTDrinker — CHANGES_REQUESTED** [review]
AMI is based on Ubuntu 20.04 which proved to have bad performance we need a clean sheet from scratch from an official Ubuntu 22.04 AMI

**Comment by IceTDrinker** [comment]
@slab-ci cpu_wasm_tes

**Comment by IceTDrinker** [comment]
@slab-ci cpu_wasm_test

**Review by IceTDrinker — APPROVED** [review]

**Pull request merged**
