### PR TITLE
fix(hlapi): pub use HlCompressible,HlExpandable

### PR DESCRIPTION
**Pull request by tmontaigu**
This is a backport

### CODE REVIEW

**Review by IceTDrinker — COMMENTED** [review]
could you add a version bump as well ?

**Review by IceTDrinker — COMMENTED** [review]
I see a lot of diffs unrelated to the PR ?

**Comment by IceTDrinker** [comment]
even for the version change

**Comment by tmontaigu** [comment]
Should be better now

**Review by IceTDrinker — APPROVED** [review]

**Comment by IceTDrinker** [comment]
> There was a conflict on the getting_started.md documentation file

Ok don't hesitate to merge once basic checks are done

**Pull request merged**
