### PR TITLE
chore(gpu): rework select to avoid using local streams

### PR DESCRIPTION
**Pull request by agnesLeroy**
closes: _please link all relevant issues_

### Check-list:

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Review by guillermo-oyarzun — APPROVED** [review]
Does this improves the issues in the multi-gpu?

**Comment by agnesLeroy** [comment]
Nope, it doesn't :disappointed:

**Comment by agnesLeroy** [comment]
I really think the multi-GPU throughput isse is related to the use of cudaDeviceSynchronize in drop for CudaVec.

**Comment by guillermo-oyarzun** [comment]
> I think the multi-GPU throughput issue is related to the use of cudaDeviceSynchronize in drop for CudaVec, I haven't tried to check though. Disabling that synchronization may lead to memory errors... I could try nevertheless to confirm it has an effect 🤔

Confirmation would be nice, even though changing that safely might involve a big refactor.

**Pull request merged**
