### PR TITLE
Am/chore/fix deps pinning

### PR DESCRIPTION
**Pull request by IceTDrinker**
Fixes https://github.com/zama-ai/tfhe-rs/issues/931

Used allow everywhere as some changes would likely be semver breaking even if some stuff is unused

### CODE REVIEW

**Comment by IceTDrinker** [comment]
I left my assert of the forward compat to test 🫠

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test
@slab-ci cpu_integer_test
@slab-ci cpu_multi_bit_test
@slab-ci cpu_wasm_test
@slab-ci csprng_randomness_testing

**Comment by IceTDrinker** [comment]
@mayeul-zama the review is to spot stuff that may look odd, CI is already in progress so no need to approve, it would just re run it

**Review by soonum — COMMENTED** [review]
Everything looks fine to me. Let's merge.

**Pull request merged**
