### PR TITLE
build(core_crypto): silence dead code warnings on test utils

### PR DESCRIPTION
**Pull request by soonum**

### CODE REVIEW

**Comment by IceTDrinker** [comment]
use chore(...) build is not part of the conventional commit stuff

**Comment by soonum** [comment]
> use chore(...) build is not part of the conventional commit stuff

Didn't read your comment :( I"ve put `test(core_crypto):...` instead.

**Comment by IceTDrinker** [comment]
test chore, whichever is ok

**Review by IceTDrinker — APPROVED** [review]
Thanks !

**Pull request merged**
